


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order-api
          uri: lb://order-api
          predicates:
            - Path=/api/order/**
        - id: payment-api
          uri: lb://payment-api
          predicates:
            - Path=/api/payment/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 60
                redis-rate-limiter.requestedTokens: 1
server:
  port: 9090


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost